version: '3'

services:
  inventorybase:
    build: .
    container_name: inventorybase
    ports:
      - 8000:8000
  items_db:
    container_name: items_db
    environment:
      MONGO_INITDB_DATABASE: ItemsDB
    image: mongo:4.4
    restart: always
  ocr:
    build: ./tess_ocr
    container_name: ocr
    ports:
      - 8001:8001

volumes:
  items_db_data: null