version: '3'

services:

  mongo:
    image: mongo:4.4
    container_name: mongo
    command: mongod --serviceExecutor adaptive
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=ItemsDB
    volumes:
      - ./load.js:/docker-entrypoint-initdb.d/load.js
    networks:
      - backend-net

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    command: 'gunicorn backend.wsgi:application -b 0.0.0.0:8000'
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - mongo
    networks:
      - backend-net

  client:
    build: ./client
    container_name: client
    restart: unless-stopped
    ports:
#      - "0.0.0.0:8080:80"
      - "0.0.0.0:8080:8080"
    depends_on:
      - backend
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge