# Generated by Django 3.0.5 on 2020-11-19 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirname', models.CharField(max_length=50, verbose_name='фамлия')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('secname', models.CharField(max_length=50, verbose_name='отчество')),
                ('position', models.CharField(max_length=50, verbose_name='должность')),
                ('rank', models.CharField(default='', max_length=50, verbose_name='звание')),
                ('gender', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=10, verbose_name='пол')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Wealth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='_id')),
                ('components', djongo.models.fields.ArrayField(model_container=main.models.Component, null=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='Наименование')),
                ('inventory_n', models.CharField(default='', max_length=100, unique=True, verbose_name='инвентарный номер')),
                ('otss_category', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('не секретно', 'не секретно')], default='1', max_length=100, verbose_name='категория ОТСС')),
                ('condition', models.CharField(choices=[('исправно', 'исправно'), ('неисправно', 'неисправно')], default='исправно', max_length=20, verbose_name='состояние')),
                ('unit_from', models.CharField(default='', max_length=50, verbose_name='подразделение, откуда поступила мат. ценность')),
                ('in_operation', models.CharField(choices=[('да', 'да'), ('нет', 'нет')], default='да', max_length=5, verbose_name='ипользуется')),
                ('fault_document_requisites', models.CharField(max_length=100, null=True, verbose_name='документы о неисправности')),
                ('date_of_receipt', models.DateField(default=datetime.date.today, verbose_name='дата поступления на учет')),
                ('number_of_receipt', models.CharField(default='', max_length=100, verbose_name='номер требования о поступлении на учет')),
                ('requisites', models.CharField(default='', max_length=100, verbose_name='реквизиты книги учета мат. ценностей')),
                ('transfer_date', models.DateField(blank=True, null=True, verbose_name='дата передачи во временное пользование')),
                ('otss_requisites', models.CharField(blank=True, max_length=100, verbose_name='реквизиты документа о категории ОТСС')),
                ('spsi_requisites', models.CharField(blank=True, max_length=100, verbose_name='реквизиты документа о прохождении СПСИ')),
                ('trnasfer_requisites', models.CharField(blank=True, max_length=100, verbose_name='реквизиты о передаче во временное пользование')),
                ('comment', models.TextField(blank=True, max_length=4000, verbose_name='примечание')),
                ('last_check', models.DateField(default=datetime.date.today, verbose_name='дата последней проверки')),
                ('responsible', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wealth', to='main.Employee', verbose_name='сотрудник, ответственный за мат. ценность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to='main.Employee', verbose_name='сотрудник, которому передали мат. ценность в пользование')),
            ],
            options={
                'verbose_name': 'материальная ценность',
                'verbose_name_plural': 'материальные ценности',
            },
        ),
    ]
